#!/bin/bash

# run docker container with httpd service and mount your current working directory to /var/www/html

#change SELinux options for folder because of permissions
chcon -Rt svirt_sandbox_file_t $(pwd)

docker run -p 80:80 -i -t -v $(pwd):/var/www/html -w /var/www/html rpitonak/httpd-container /bin/bash -c "/usr/sbin/httpd; /bin/bash"
