#!/bin/bash

# run docker container with httpd service and mount your current working directory to /var/www/html

#change SELinux options for folder because of permissions
chcon -Rt svirt_sandbox_file_t $(pwd)

docker run -p 8080:8080 -i -t -v $(pwd):/var/www/ -w /var/www/ rpitonak/httpd /bin/bash -c "/usr/sbin/httpd; /bin/bash"
